/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsRouteImport } from './routes/es'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewMeadowRouteImport } from './routes/preview/meadow'

const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMeadowRoute = PreviewMeadowRouteImport.update({
  id: '/preview/meadow',
  path: '/preview/meadow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/es': typeof EsRoute
  '/preview/meadow': typeof PreviewMeadowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/es': typeof EsRoute
  '/preview/meadow': typeof PreviewMeadowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/es': typeof EsRoute
  '/preview/meadow': typeof PreviewMeadowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/es' | '/preview/meadow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/es' | '/preview/meadow'
  id: '__root__' | '/' | '/es' | '/preview/meadow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsRoute: typeof EsRoute
  PreviewMeadowRoute: typeof PreviewMeadowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/meadow': {
      id: '/preview/meadow'
      path: '/preview/meadow'
      fullPath: '/preview/meadow'
      preLoaderRoute: typeof PreviewMeadowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsRoute: EsRoute,
  PreviewMeadowRoute: PreviewMeadowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
